<?php

namespace App\Exceptions;

use App\Mail\ExceptionMail;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
    public function render($request, Throwable $e)
    {
        if($this->is404($e)) {
            $this->log404($request);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    /**
     * Report or log an exception.
     *
     * @param \Throwable $exception
     * @return void
     *
     * @throws Exception
     */
    public function report(Throwable $exception)
    {
        parent::report($exception);

        if (env('MAIL_HOST') && env('APP_ENV') == 'production' && $this->shouldReport($exception)) {
            try {
                $this->sendEmail($exception); // sends an email
            } catch (Exception $e) {
                Log::alert('Errore invio email segnalazione errore:' . $e->getMessage());
            }
        }

    }

    public function sendEmail(Throwable $exception)
    {
        try {
            $mailable = new ExceptionMail($exception);
            if (Auth::check()) {
                $mailable->replyTo(Auth::user()->email, Auth::user()->nominativo());
            }
            Mail::to('andicot@gmail.com')->send($mailable);
        } catch (Exception $ex) {
            dd($ex);
        }
    }

    private function is404($exception)
    {
        return $exception instanceof \Illuminate\Database\Eloquent\ModelNotFoundException
            || $exception instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
    }

    private function log404($request)
    {
        $error = [
            'url'    => $request->url(),
            'method' => $request->method(),
            'data'   => $request->all(),
        ];

        $message = '404: ' . $error['url'] . "\n" . json_encode($error, JSON_PRETTY_PRINT);

        Log::debug($message);
    }


}

